// Mocks generated by Mockito 5.2.0 from annotations
// in fluttertemplate/test/home_cubit_test.dart.
// Do not manually edit this file.

import 'package:fluttertemplate/src/domain/entities/todo_item_entity.dart'
    as _i4;
import 'package:fluttertemplate/src/domain/repositories/home_repository/home_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

import 'home_cubit_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeHomeRepository_0 extends _i1.Fake implements _i2.HomeRepository {}

/// A class which mocks [MockHomeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockHomeUseCase extends _i1.Mock implements _i3.MockHomeUseCase {
  MockMockHomeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get homeRepository =>
      (super.noSuchMethod(Invocation.getter(#homeRepository),
          returnValue: _FakeHomeRepository_0()) as _i2.HomeRepository);
  @override
  List<_i4.ToDoItemEntity> getTodoItemsLocal() =>
      (super.noSuchMethod(Invocation.method(#getTodoItemsLocal, []),
          returnValue: <_i4.ToDoItemEntity>[]) as List<_i4.ToDoItemEntity>);
  @override
  bool saveTodoItemsLocal(List<_i4.ToDoItemEntity>? items) =>
      (super.noSuchMethod(Invocation.method(#saveTodoItemsLocal, [items]),
          returnValue: false) as bool);
  @override
  bool isHasData() =>
      (super.noSuchMethod(Invocation.method(#isHasData, []), returnValue: false)
          as bool);
}
